site_name: Pronto Api
theme:
  name: material
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    - tables
    - attr_list
    - md_in_html
    - pymdownx.superfences
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: pink
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: pink
      accent: inidigo
markdown_extensions:
  - toc:
      permalink: true
      title: Tabla

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/conpronto/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/conpronto/
    - icon: fontawesome/brands/github
      link: https://github.com/conpronto 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
   
copyright: |
  &copy; 2023 <a href="https://conpronto.com/"  target="_blank" rel="noopener">PRONTO</a>